# Generated by Django 4.1.7 on 2023-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_paymentsuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuser',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
