# Generated by Django 4.1.7 on 2023-02-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentsuser_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentsuser',
            table='users',
        ),
    ]
