db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=9639
        - POSTGRES_DB=payments
        - PGDATA=/var/lib/postgresql/data
    volumes:
        - ./postgres/pgdata:/var/lib/postgresql/data
