# Generated by Django 4.1.7 on 2023-02-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0003_alter_balance_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='balances',
        ),
    ]
